// Date: 2013/11/18 21:36:52
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package net.minecraft.src.nucleareal.animalcrossing.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelMapleAkaha extends ModelBiped
{
	// fields
	ModelRenderer head;
	ModelRenderer body;
	ModelRenderer rightarm;
	ModelRenderer leftarm;
	ModelRenderer rightleg;
	ModelRenderer leftleg;
	ModelRenderer Pants;
	ModelRenderer Hp;
	ModelRenderer Breas;
	ModelRenderer Skirt1;
	ModelRenderer Skirt2;
	ModelRenderer Skirt3;
	ModelRenderer Skirt4;
	ModelRenderer SkirtB1;
	ModelRenderer SkirtB3;
	ModelRenderer SkirtB2;
	ModelRenderer SkirtB4;

	public ModelMapleAkaha()
	{
		super();

		textureWidth = 256;
		textureHeight = 256;

		bipedHeadwear = new ModelRenderer(this, 0, 0);

		bipedHead = new ModelRenderer(this, 0, 0);
		bipedHead.addBox(-4F, -8F, -4F, 8, 8, 8);
		bipedHead.setRotationPoint(0F, 0F, 0F);
		bipedHead.setTextureSize(256, 256);
		bipedHead.mirror = true;
		setRotation(bipedHead, 0F, 0F, 0F);
		bipedBody = new ModelRenderer(this, 12, 16);
		bipedBody.addBox(-3.5F, 0F, -2F, 7, 12, 3);
		bipedBody.setRotationPoint(0F, 0F, 0F);
		bipedBody.setTextureSize(256, 256);
		bipedBody.mirror = true;
		setRotation(bipedBody, 0F, 0F, 0F);
		bipedRightArm = new ModelRenderer(this, 32, 16);
		bipedRightArm.addBox(-0.5F, -1.5F, -1.5F, 2, 12, 3);
		bipedRightArm.setRotationPoint(-4.5F, 1.5F, -0.5F);
		bipedRightArm.setTextureSize(256, 256);
		bipedRightArm.mirror = true;
		setRotation(bipedRightArm, 0F, 0F, 0.2617994F);
		bipedLeftArm = new ModelRenderer(this, 32, 16);
		bipedLeftArm.addBox(-1.5F, -1.5F, -1.5F, 2, 12, 3);
		bipedLeftArm.setRotationPoint(4.5F, 1.5F, -0.5F);
		bipedLeftArm.setTextureSize(256, 256);
		bipedLeftArm.mirror = false;
		setRotation(bipedLeftArm, 0F, 0F, -0.2617994F);
		bipedRightLeg = new ModelRenderer(this, 0, 16);
		bipedRightLeg.addBox(-2F, 0F, -2F, 3, 12, 3);
		bipedRightLeg.setRotationPoint(-1.5F, 12F, 0F);
		bipedRightLeg.setTextureSize(256, 256);
		bipedRightLeg.mirror = true;
		setRotation(bipedRightLeg, 0F, 0F, -0.0216421F);
		bipedLeftLeg = new ModelRenderer(this, 0, 16);
		bipedLeftLeg.addBox(-1F, 0F, -2F, 3, 12, 3);
		bipedLeftLeg.setRotationPoint(1.5F, 12F, 0F);
		bipedLeftLeg.setTextureSize(256, 256);
		bipedLeftLeg.mirror = false;
		setRotation(bipedLeftLeg, 0F, 0F, 0.0216421F);
		Pants = new ModelRenderer(this, 0, 31);
		Pants.addBox(0F, 0F, -1F, 3, 3, 2);
		Pants.setRotationPoint(0F, 8.5F, -0.9F);
		Pants.setTextureSize(256, 256);
		Pants.mirror = true;
		setRotation(Pants, 0F, 0F, 0.7853982F);
		Hp = new ModelRenderer(this, 0, 36);
		Hp.addBox(-3F, 0F, 0F, 6, 3, 2);
		Hp.setRotationPoint(0F, 9.5F, -0.8F);
		Hp.setTextureSize(256, 256);
		Hp.mirror = true;
		setRotation(Hp, 0.5235988F, 0F, 0F);
		Breas = new ModelRenderer(this, 42, 16);
		Breas.addBox(-3F, 0F, 0F, 6, 3, 3);
		Breas.setRotationPoint(0F, 4F, -3.7F);
		Breas.setTextureSize(256, 256);
		Breas.mirror = true;
		setRotation(Breas, 0.9599311F, 0F, 0F);
		Skirt1 = new ModelRenderer(this, 0, 41);
		Skirt1.addBox(-3F, 7F, 2.5F, 6, 8, 1);
		Skirt1.setRotationPoint(0F, 0F, -0.5F);
		Skirt1.setTextureSize(256, 256);
		Skirt1.mirror = true;
		setRotation(Skirt1, -0.5235988F, 0F, 0F);
		Skirt2 = new ModelRenderer(this, 0, 41);
		Skirt2.addBox(-3F, 7F, 2.5F, 6, 8, 1);
		Skirt2.setRotationPoint(0F, 0F, -0.5F);
		Skirt2.setTextureSize(256, 256);
		Skirt2.mirror = true;
		setRotation(Skirt2, -0.5235988F, 3.141593F, 0F);
		Skirt3 = new ModelRenderer(this, 0, 41);
		Skirt3.addBox(-1.5F, 8F, 0.5F, 3, 8, 1);
		Skirt3.setRotationPoint(0F, 0F, -0.5F);
		Skirt3.setTextureSize(256, 256);
		Skirt3.mirror = true;
		setRotation(Skirt3, -0.5235988F, 1.570796F, 0F);
		Skirt4 = new ModelRenderer(this, 0, 41);
		Skirt4.addBox(-1.5F, 8F, 0.5F, 3, 8, 1);
		Skirt4.setRotationPoint(0F, 0F, -0.5F);
		Skirt4.setTextureSize(256, 256);
		Skirt4.mirror = true;
		setRotation(Skirt4, -0.5235988F, -1.570796F, 0F);
		SkirtB1 = new ModelRenderer(this, 15, 41);
		SkirtB1.addBox(-4.5F, 7.5F, 0.6F, 5, 8, 1);
		SkirtB1.setRotationPoint(0F, 0F, -0.5F);
		SkirtB1.setTextureSize(256, 256);
		SkirtB1.mirror = true;
		setRotation(SkirtB1, -0.4363323F, 0.6108652F, 0F);
		SkirtB3 = new ModelRenderer(this, 15, 41);
		SkirtB3.addBox(-4.5F, 7.5F, 0.6F, 5, 8, 1);
		SkirtB3.setRotationPoint(0F, 0F, -0.5F);
		SkirtB3.setTextureSize(256, 256);
		SkirtB3.mirror = true;
		setRotation(SkirtB3, -0.4363323F, -2.530727F, 0F);
		SkirtB2 = new ModelRenderer(this, 15, 41);
		SkirtB2.addBox(-1F, 7.5F, 0.2F, 5, 8, 1);
		SkirtB2.setRotationPoint(0F, 0F, -0.5F);
		SkirtB2.setTextureSize(256, 256);
		SkirtB2.mirror = true;
		setRotation(SkirtB2, -0.4363323F, 2.443461F, 0F);
		SkirtB4 = new ModelRenderer(this, 15, 41);
		SkirtB4.addBox(-1F, 7.5F, 0.2F, 5, 8, 1);
		SkirtB4.setRotationPoint(0F, 0F, -0.5F);
		SkirtB4.setTextureSize(256, 256);
		SkirtB4.mirror = true;
		setRotation(SkirtB4, -0.4363323F, -0.6981317F, 0F);

		bipedBody.addChild(Pants);
		bipedBody.addChild(Hp);
		bipedBody.addChild(Breas);
		bipedBody.addChild(Skirt1);
		bipedBody.addChild(Skirt2);
		bipedBody.addChild(Skirt3);
		bipedBody.addChild(Skirt4);
		bipedBody.addChild(SkirtB1);
		bipedBody.addChild(SkirtB2);
		bipedBody.addChild(SkirtB3);
		bipedBody.addChild(SkirtB4);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		/*head.render(f5);
		body.render(f5);
		rightarm.render(f5);
		leftarm.render(f5);
		rightleg.render(f5);
		leftleg.render(f5);*/
		/*Pants.render(f5);
		Hp.render(f5);
		Breas.render(f5);
		Skirt1.render(f5);
		Skirt2.render(f5);
		Skirt3.render(f5);
		Skirt4.render(f5);
		SkirtB1.render(f5);
		SkirtB3.render(f5);
		SkirtB2.render(f5);
		SkirtB4.render(f5);*/
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

}
